name: Remote Control

on:
  workflow_dispatch:

jobs:
  trigger-remote-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Controler
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_REMOTE_CONTROLE }}" \
            https://api.github.com/WehrliDavid/repos/TestModelsRepo/dispatches \
            -d '{"event_type":"update","client_payload":{"ref":"main"}}'
